<?php
return [
    'dataflag' => [
        'TRANSACTION_FLAG_CLEARING' => 1,
        'TRANSACTION_FLAG_GUARANTEE' => 2,
        'TRANSACTION_FLAG_3DSECURE' => 3,
        'TRANSACTION_FLAG_EXT_API' => 4,
        'TRANSACTION_FLAG_DEMO' => 5,
        'TRANSACTION_FLAG_AUTHORIZATION' => 6,
        'TRANSACTION_FLAG_ACCRUAL' => 7,
        'TRANSACTION_FLAG_STAKEHOLDER_EVALUATED' => 8,
        'TRANSACTION_FLAG_BASKET_EVALUATED' => 9,
        'TRANSACTION_FLAG_BASKET_ITEM_EVALUATED' => 10,
        'TRANSACTION_FLAG_SECUCORE' => 11,
        'TRANSACTION_FLAG_CHECKOUT' => 12,
        'TRANSACTION_FLAG_LVP' => 13,
        'TRANSACTION_FLAG_TRA' => 14,
        'TRANSACTION_FLAG_MIT' => 15
    ]
];
